'use client';

import {useCallback, useEffect, useState} from 'react';
import {ArrowDownToLine, ArrowRight, Bell, Check, ChevronRight, ClipboardList, ExternalLink, FileText, Leaf, LoaderCircle, Pause, Play, RefreshCw, Search, ShieldCheck, SlidersHorizontal, Sparkles, X} from 'lucide-react';

type Job = {id:string; company:string; title:string; location:string; term:string; url:string; sources:string; state:string};
type Profile = {id:string; verified:number; synthetic:number; provider_consent:boolean; content:{name:string; contact:string; heading:string; facts:{id:string;text:string;source:string}[]; bullets:{id:string;text:string;source_fact_ids:string[]}[]; answers:Record<string,string>}};
type Candidate = {candidate_id:string;replacement_text:string;source_fact_ids:string[];eligible:boolean;gate_reason:string|null;score:number;evaluation:{support:string;provider:string;mocked:boolean;reason:string;relevance:number;clarity:number;specificity:number;concision:number}};
type Packet = {id:string;hash:string;status:string;content:{job:Job;name:string;contact:string;heading:string;synthetic:boolean;selected_texts:string[];answers:Record<string,string>;missing_answers:string[];eligibility:string;generator:string;judge:string;destination:string;decisions:{bullet_id:string;candidates:Candidate[];selected:string;reason:string}[];review:{approved:boolean;mocked:boolean;reason:string};snapshot:{text:string;provenance:string}}};
type Dashboard = {jobs:Job[];profiles:Profile[];packets:{id:string;job_id:string;status:string}[];tasks:{id:string;job_id:string;status:string;error:string|null}[];sources:{id:string;error:string|null;checked:number}[];notifications:{id:string;packet_id:string;title:string;created:number;delivered:number;error:string|null}[];mode:string;worker_paused:boolean;provider_configuration:Record<string,unknown>;notifications_enabled:boolean;notification_destination:string;public_app_url:string};
type Detail = Job & {snapshot: {text:string;provenance:string;created:number}|null};

async function api(path:string, body?:unknown) {
  const response = await fetch('/api'+path, {method:body===undefined?'GET':'POST', headers:{'Content-Type':'application/json','X-Apply-Desk':'1'}, body:body===undefined?undefined:JSON.stringify(body)});
  const data = await response.json();
  if (!response.ok) throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));
  return data;
}
const nice = (s:string) => s.toLowerCase().replaceAll('_',' ');

export default function Home() {
  const [data,setData] = useState<Dashboard|null>(null);
  const [auth,setAuth] = useState(false);
  const [pass,setPass] = useState('');
  const [tab,setTab] = useState('queue');
  const [query,setQuery] = useState('');
  const [source,setSource] = useState('all');
  const [active,setActive] = useState<string|null>(null);
  const [detail,setDetail] = useState<Detail|null>(null);
  const [packet,setPacket] = useState<Packet|null>(null);
  const [reviewTab,setReviewTab] = useState('resume');
  const [profileId,setProfileId] = useState('');
  const [profileJson,setProfileJson] = useState('');
  const [snapshot,setSnapshot] = useState('');
  const [error,setError] = useState('');
  const [message,setMessage] = useState('');
  const [busy,setBusy] = useState('');
  const [limit,setLimit] = useState(30);
  const load = useCallback(async () => {
    const d = await api('/dashboard'); setData(d); setAuth(true);
    setProfileId(prev => prev || d.profiles.find((p:Profile)=>p.verified)?.id || '');
    setProfileJson(prev => prev || JSON.stringify(d.profiles[0]?.content,null,2));
    return d as Dashboard;
  },[]);
  useEffect(()=>{load().catch(()=>setAuth(false));},[load]);
  useEffect(()=>{ if(!auth)return; const timer=setInterval(()=>load().catch(()=>{}),4000);return()=>clearInterval(timer);},[auth,load]);
  async function run(label:string, fn:()=>Promise<void>) {setBusy(label);setError('');setMessage('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
  const openPacket = useCallback(async (id:string)=>{const p=await api('/packets/'+id);setPacket(p);setActive(p.content.job.id);setTab('queue');setDetail(await api('/jobs/'+p.content.job.id));setReviewTab('resume');},[]);
  useEffect(()=>{if(!auth)return;const id=new URLSearchParams(window.location.search).get('packet');if(id)openPacket(id).catch(e=>setError(e.message));},[auth,openPacket]);
  async function select(job:Job) {setActive(job.id);setPacket(null);setDetail(null);setSnapshot('');const d=await api('/jobs/'+job.id);setDetail(d);const p=data?.packets.find(p=>p.job_id===job.id);if(p)setPacket(await api('/packets/'+p.id));}
  async function reloadDetail(){if(active)setDetail(await api('/jobs/'+active));await load();}
  async function prepare(){if(!active)return;await api('/jobs/'+active+'/prepare',{profile_id:profileId});const d=await load();const p=d.packets.find(p=>p.job_id===active);if(p)await openPacket(p.id);else setMessage('Preparation queued. Results and errors appear below; refresh the review when ready.');}
  async function fixture(action:'disclose'|'submit'){if(!packet)return;const approval=await api('/packets/'+packet.id+'/approvals',{action});await api('/packets/'+packet.id+'/fixture',{approval_id:approval.id,operation:action==='submit'?'submit':'fill'});await openPacket(packet.id);await load();}

  if(!auth) return <main className="login"><div className="login-card"><div className="brand"><span className="brand-icon"><Leaf size={24}/></span>apply desk<span className="beta">MVP</span></div><p className="eyebrow">YOUR NEXT CHAPTER</p><h1>A little less applying.<br/>A little more possibility.</h1><p className="muted">A private workspace for internship discovery, evidence-backed resume edits, and application packets.</p><form onSubmit={e=>{e.preventDefault();run('Signing in',async()=>{await api('/login',{password:pass});await load();});}}><label>Local dashboard passphrase<input type="password" value={pass} onChange={e=>setPass(e.target.value)} autoComplete="current-password" required/></label><button className="primary" disabled={!!busy}>Open workspace <ArrowRight size={17}/></button></form>{error&&<p className="error">{error}</p>}<p className="footnote">Find your generated passphrase in <code>data/auth-token.txt</code>, or use APP_PASSWORD from your configuration.</p></div><div className="login-art"><span>DISCOVER → TAILOR → REVIEW</span><div className="paper-art"><Leaf size={36}/><h2>Your experience.<br/>Thoughtfully presented.</h2><div/><div/><div/><small>ChatGPT proposes. Laya reviews. You decide.</small></div></div></main>;
  if(!data)return null;
  const filtered=data.jobs.filter(j=>(source==='all'||j.sources?.includes(source))&&[j.company,j.title,j.location].join(' ').toLowerCase().includes(query.toLowerCase()));
  const selectedProfile=data.profiles.find(p=>p.id===profileId);
  const activeTasks=data.tasks.filter(t=>t.job_id===active);
  const inProgress=data.tasks.filter(t=>['QUEUED','RUNNING'].includes(t.status)).length;
  const navigation=[{id:'queue',label:'Opportunity queue',icon:ClipboardList},{id:'profile',label:'Master profile',icon:FileText},{id:'inbox',label:'Packet inbox',icon:Bell}];

  return <div className="shell"><aside className="sidebar"><div className="brand"><span className="brand-icon"><Leaf size={22}/></span>apply desk</div><div className="workspace-label">PERSONAL WORKSPACE</div><nav>{navigation.map(({id,label,icon:Icon})=><button key={id} className={tab===id?'nav active':'nav'} onClick={()=>setTab(id)}><Icon size={18}/>{label}{id==='inbox'&&<span className="count">{data.notifications.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="mode"><span className="dot"/>{data.mode==='demo'?'Demo workspace':'Provider workspace'}</div><p>Live applications disabled.<br/>Your source stays untouched.</p><button className="text-button" onClick={()=>run('Signing out',async()=>{await api('/logout',{});setAuth(false);setData(null);})}>Sign out</button></div></aside>
  <main className="main"><header className="topbar"><span>Workspace <ChevronRight size={14}/> {navigation.find(n=>n.id===tab)?.label}</span><div><span className="status-pill">{data.mode==='demo'?'Synthetic profile · Mock reviews':'Configured providers'}</span><span className="avatar">A</span></div></header>
  {error&&<div className="notice error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}{message&&<div className="notice" role="status">{message}<button onClick={()=>setMessage('')} aria-label="Dismiss message"><X size={16}/></button></div>}
  <div className="page-heading"><div><p className="eyebrow">INTERNSHIP SEASON / 2027</p><h1>{tab==='queue'?'Make your next move.':tab==='profile'?'Start with the facts.':'Ready when you are.'}</h1><p className="muted">{tab==='queue'?'Find a role. Tailor with evidence. Apply with confidence.':tab==='profile'?'Your verified experience is the source of every resume edit.':'Application packets and links, in one place.'}</p></div><button className="secondary" disabled={!!busy} onClick={()=>run('Refreshing sources',async()=>{const r=await api('/refresh',{});await load();setMessage(r.map((x:{source:string;error?:string;added?:number;unchanged?:boolean})=>`${x.source}: ${x.error?'refresh failed':x.unchanged?'unchanged':`${x.added} new`}`).join(' · '));})}><RefreshCw size={16} className={busy==='Refreshing sources'?'spin':''}/>Refresh sources</button></div>
  {busy&&<div className="working"><LoaderCircle size={16} className="spin"/>{busy}…</div>}
  {tab==='queue'&&<><section className="metrics"><div><span>IN YOUR QUEUE</span><strong>{data.jobs.length.toLocaleString()}<small>roles discovered</small></strong></div><div><span>CONNECTED SOURCES</span><strong>03<small>public GitHub feeds</small></strong></div><div><span>APPLICATION PACKETS</span><strong>{String(data.packets.length).padStart(2,'0')}<small>{inProgress?`${inProgress} preparing`:'ready for your review'}</small></strong></div></section>
  <section className="workflow"><span className="workflow-icon"><Sparkles size={20}/></span><div><strong>A second opinion on every edit.</strong><p>Three alternatives + the original → independent Laya review → deterministic selection → full resume review.</p></div><span className="pill">{data.mode==='demo'?'MOCKED IN DEMO':'CONTENT REVIEW'}</span></section>
  <div className={active?'queue-layout has-detail':'queue-layout'}><section className="job-panel"><div className="panel-heading"><h2>Opportunity queue <span>{filtered.length}</span></h2><button className="icon-button" title={data.worker_paused?'Resume preparation':'Pause preparation'} onClick={()=>run('Updating worker',async()=>{await api('/worker/toggle',{});await load();})}>{data.worker_paused?<Play size={17}/>:<Pause size={17}/>}</button></div><div className="filters"><label className="search"><Search size={16}/><input aria-label="Search jobs" placeholder="Search role, company, or location" value={query} onChange={e=>{setQuery(e.target.value);setLimit(30);}}/></label><label className="source-filter"><SlidersHorizontal size={15}/><select aria-label="Filter source" value={source} onChange={e=>{setSource(e.target.value);setLimit(30);}}><option value="all">All sources</option><option value="simplify-summer">Simplify · Summer</option><option value="simplify-offseason">Simplify · Off-season</option><option value="zapply">zapply · 2027</option></select></label></div>
  <div className="job-list">{filtered.slice(0,limit).map((job,i)=><button key={job.id} className={active===job.id?'job-card selected':'job-card'} onClick={()=>run('Opening role',()=>select(job))}><div className={'company-mark color-'+i%4}>{job.company.replace(/[^A-Za-z]/g,'').slice(0,2).toUpperCase()}</div><div className="job-copy"><div className="company-line">{job.company}<span>{job.sources?.includes('simplify-offseason')?'Off-season':'2027'}</span></div><h3>{job.title}</h3><p>{job.location}</p><div className="tags"><span>{job.sources?.split(',').map(s=>s==='zapply'?'zapply':s==='simplify-summer'?'Simplify Summer':'Simplify Off-season').join(' · ')}</span>{job.state!=='DISCOVERED'&&<span className="state-tag">{nice(job.state)}</span>}</div></div><ChevronRight size={18}/></button>)}{!filtered.length&&<div className="empty">No matching roles. Try a broader search.</div>}</div>{filtered.length>limit&&<button className="load-more" onClick={()=>setLimit(limit+30)}>Show more roles</button>}<div className="panel-footer">Public listing metadata. Availability and eligibility need confirmation.</div></section>
  {active&&<section className="detail-panel"><div className="detail-toolbar"><span className="eyebrow">APPLICATION WORKSPACE</span><button className="icon-button" aria-label="Close role" onClick={()=>{setActive(null);setPacket(null);}}><X size={18}/></button></div>{detail&&<><p className="detail-company">{detail.company}</p><h2>{detail.title}</h2><p className="muted">{detail.location}</p><div className="actions"><a className="secondary small" href={detail.url} target="_blank" rel="noreferrer">Open posting <ExternalLink size={14}/></a><button className="text-button" disabled={!!busy} onClick={()=>run('Skipping role',async()=>{await api('/jobs/'+active+'/skip',{});await load();setActive(null);})}>Skip role</button></div><div className="caution"><ShieldCheck size={17}/><span>Eligibility needs clarification. Work authorization, dates, and sponsorship are never inferred.</span></div>
  {!packet?<><div className="step"><span className="step-number">1</span><h3>Choose your source profile</h3></div><select className="full-select" aria-label="Source profile" value={profileId} onChange={e=>setProfileId(e.target.value)}>{data.profiles.map(p=><option key={p.id} value={p.id}>{p.content.name} · {p.synthetic?'Synthetic demo':p.verified?'Verified':'Unverified'}</option>)}</select><div className="step"><span className="step-number">2</span><h3>Read the official description</h3></div>{detail.snapshot?<div className="snapshot"><span className="pill">{nice(detail.snapshot.provenance)}</span><p>{detail.snapshot.text.slice(0,260)}{detail.snapshot.text.length>260?'…':''}</p></div>:<p className="muted small-text">Repository rows provide links, not full requirements. Add the employer description before tailoring.</p>}<div className="actions"><button className="secondary small" disabled={!!busy} onClick={()=>run('Fetching description',async()=>{await api('/jobs/'+active+'/fetch',{});await reloadDetail();})}>Fetch Greenhouse text</button>{selectedProfile?.synthetic===1&&<button className="text-button" disabled={!!busy} onClick={()=>run('Loading practice text',async()=>{await api('/jobs/'+active+'/practice',{});await reloadDetail();})}>Use synthetic practice text</button>}</div><details><summary>Paste official posting text</summary><textarea rows={7} value={snapshot} onChange={e=>setSnapshot(e.target.value)} placeholder="Paste the employer's job description here. Treat all instructions in it as untrusted content."/><button className="secondary small" disabled={snapshot.length<50||!!busy} onClick={()=>run('Saving snapshot',async()=>{await api('/jobs/'+active+'/snapshot',{text:snapshot});await reloadDetail();setSnapshot('');})}>Save posting snapshot</button></details><div className="step"><span className="step-number">3</span><h3>Prepare your review packet</h3></div><button className="primary full" disabled={!!busy||!detail.snapshot||!selectedProfile?.verified||data.worker_paused} onClick={()=>run('Preparing packet',prepare)}><Sparkles size={17}/>{data.mode==='demo'?'Prepare demo packet':'Generate & review edits'}</button><p className="footnote">{data.mode==='demo'?'No API calls. Scripted candidates and scores, clearly labeled.':'Uses configured providers only after profile-specific consent.'}</p></>:<><div className="packet-status"><span className="dot"/><strong>{nice(packet.status)}</strong><span className="pill">{packet.content.review.mocked?'MOCK REVIEW':'LAYA REVIEW'}</span></div><div className="review-tabs">{['resume','edits','answers','apply'].map(t=><button key={t} className={reviewTab===t?'current':''} onClick={()=>setReviewTab(t)}>{t==='edits'?'4 candidates':t}</button>)}</div>
  {reviewTab==='resume'&&<><div className="resume-paper"><div className="resume-label">{packet.content.synthetic?'SYNTHETIC DEMO · NOT FOR APPLICATION':'DRAFT · REVIEW BEFORE APPLYING'}</div><h2>{packet.content.name}</h2><p>{packet.content.contact}</p><h3>{packet.content.heading}</h3><ul>{packet.content.selected_texts.map((t,i)=><li key={i}>{t}</li>)}</ul></div><div className="review-result"><ShieldCheck size={18}/><div><strong>{packet.content.review.approved?'Final content review passed':'Human review required'}{packet.content.review.mocked?' (mock)':''}</strong><p>{packet.content.review.reason}</p></div></div><div className="actions"><a className="primary small" href={'/api/packets/'+packet.id+'/resume.pdf'}><ArrowDownToLine size={15}/>Resume PDF</a><a className="secondary small" href={'/api/packets/'+packet.id+'/packet.zip'}>Full packet .zip</a></div><p className="footnote">Immutable packet · {packet.hash.slice(0,16)} · Edits require a new review.</p></>}
  {reviewTab==='edits'&&<div>{packet.content.decisions.map((d,i)=><div className="decision" key={d.bullet_id}><h3>Bullet {i+1}</h3><p className="muted small-text">{d.reason}</p>{d.candidates.map((c,j)=><div key={c.candidate_id} className={'candidate '+(d.selected===c.candidate_id?'winner':'')+(!c.eligible?' rejected':'')}><div className="candidate-top"><strong>{j===0?'Original':`Alternative ${j}`}</strong><span>{c.score.toFixed(0)} / 100 {c.evaluation.mocked?'· mock':''}</span></div><p>{c.replacement_text}</p><div className="candidate-bottom"><span>{d.selected===c.candidate_id?<><Check size={13}/>Selected</>:!c.eligible?<><X size={13}/>Rejected</>:c.evaluation.support.toLowerCase()}</span><small>Evidence: {c.source_fact_ids.join(', ')}</small></div>{c.gate_reason&&<p className="rejection-reason">{c.gate_reason}</p>}<details><summary>Score breakdown</summary><p className="footnote">Relevance {c.evaluation.relevance} · Clarity {c.evaluation.clarity} · Specificity {c.evaluation.specificity} · Concision {c.evaluation.concision}</p><p className="footnote">{c.evaluation.reason}</p></details></div>)}</div>)}</div>}
  {reviewTab==='answers'&&<><h3>Confirmed application answers</h3>{Object.keys(packet.content.answers).length?Object.entries(packet.content.answers).map(([q,a])=><div className="answer" key={q}><strong>{nice(q)}</strong><p>{a}</p><button className="text-button" onClick={()=>run('Copying answer',async()=>{await navigator.clipboard.writeText(a);setMessage('Answer copied.');})}>Copy answer</button></div>):<p className="muted">No application answers have been confirmed yet.</p>}<div className="caution"><span>Confirm before applying: {packet.content.missing_answers.map(nice).join(', ')||'employer-specific eligibility and questions'}.</span></div><h3>Posting snapshot</h3><span className="pill">{nice(packet.content.snapshot.provenance)}</span><pre className="posting-text">{packet.content.snapshot.text}</pre></>}
  {reviewTab==='apply'&&<><div className="handoff"><FileText size={25}/><h3>Your application, ready to take over.</h3><p>Download the resume and answers, open the posting, and complete the employer’s form from your device.</p><a className="primary" href={detail.url} target="_blank" rel="noreferrer">Open application <ExternalLink size={15}/></a></div><p className="footnote">Computer-use applications are disabled in this MVP. No typing, upload, or submission to employers happens here.</p>{packet.content.synthetic&&<details className="fixture"><summary>Try the local approval simulation</summary><p className="small-text">Synthetic data only. Destination bound in the simulated approval:</p><code className="url-text">{packet.content.destination}</code><p className="small-text">Approvals expire after 10 minutes and can be used once. This simulates a form; it never contacts this destination.</p>{packet.status==='DEMO_READY'&&<button className="secondary" disabled={!!busy} onClick={()=>run('Simulating approved disclosure',()=>fixture('disclose'))}>Approve demo disclosure & fill</button>}{packet.status==='WAITING_FOR_SUBMIT_APPROVAL'&&<><p>Exact packet is now filled in the fixture.</p><button className="primary" disabled={!!busy} onClick={()=>run('Simulating approved submission',()=>fixture('submit'))}>Approve demo submission</button></>}{packet.status==='DEMO_SUBMITTED'&&<p className="success">Fixture receipt recorded. No real application submitted.</p>}</details>}</>}
  <button className="text-button revise" onClick={()=>{setPacket(null);setReviewTab('resume');}}>Prepare another version</button></>}
  {activeTasks.length>0&&<details className="tasks"><summary>Preparation history</summary>{activeTasks.map(t=><p key={t.id} className={t.error?'error small-text':'small-text'}>{nice(t.status)}{t.error?' — '+t.error:''}</p>)}<button className="text-button" onClick={()=>run('Loading latest packet',async()=>{const d=await load();const p=d.packets.find(p=>p.job_id===active);if(p)await openPacket(p.id);})}>Open latest result</button></details>}</>}</section>}</div>
  <div className="source-status">{data.sources.map(s=><span key={s.id}><span className={s.error?'dot warning':'dot'}/>{s.id}{s.error?' · refresh failed':' · snapshot saved'}</span>)}</div></>}
  {tab==='profile'&&<div className="profile-grid"><section className="panel"><h2>Verified source material</h2><p className="muted">Import a structured profile below. Review every fact, then verify it. Saving creates a new version; existing source material is never overwritten.</p>{data.profiles.map(p=><div className="profile-card" key={p.id}><div><h3>{p.content.name}</h3><span className="pill">{p.synthetic?'SYNTHETIC':p.verified?'VERIFIED':'NEEDS VERIFICATION'}</span></div><p>{p.content.contact}</p><ul>{p.content.facts.map(f=><li key={f.id}><strong>{f.id}</strong> {f.text}<small>{f.source}</small></li>)}</ul><div className="actions"><button className="secondary small" onClick={()=>{setProfileId(p.id);setProfileJson(JSON.stringify(p.content,null,2));setMessage('Profile selected.');}}>Use this profile</button>{!p.verified&&<button className="primary small" disabled={!!busy} onClick={()=>run('Verifying facts',async()=>{const r=await api('/profiles/'+p.id+'/verify',{confirmed:true});setProfileId(r.id);await load();})}>I verify these facts and answers</button>}{!!p.verified&&data.mode!=='demo'&&!p.provider_consent&&<button className="secondary small" onClick={()=>run('Saving provider consent',async()=>{await api('/profiles/'+p.id+'/consent',{confirmed:true});await load();})}>Allow processing by providers shown</button>}</div></div>)}</section><section className="panel"><h2>Import or revise a profile</h2><p className="muted small-text">Replace the example with your facts, project or experience heading, and bullets. Unknown application answers should stay absent. PDF parsing and a full resume editor are outside this slice.</p><textarea className="json-editor" rows={24} aria-label="Profile JSON" value={profileJson} onChange={e=>setProfileJson(e.target.value)}/><button className="primary" disabled={!!busy} onClick={()=>run('Importing profile',async()=>{const r=await api('/profiles',JSON.parse(profileJson));setProfileId(r.id);await load();setMessage('Imported locally. Verify facts before generating edits.');})}>Save as unverified version <ArrowRight size={16}/></button><h3>Provider processing scope</h3><pre className="config">{JSON.stringify(data.provider_configuration,null,2)}</pre><p className="footnote">In demo mode, only the synthetic fixture can be tailored. Importing your profile makes no external API calls.</p></section></div>}
  {tab==='inbox'&&<div className="profile-grid"><section className="panel"><h2>Your packet inbox <span className="pill">{data.notifications.length}</span></h2>{data.notifications.length?data.notifications.map(n=><button className="inbox-row" key={n.id} onClick={()=>run('Opening packet',()=>openPacket(n.packet_id))}><span className="inbox-icon"><FileText size={20}/></span><div><strong>{n.title}</strong><p>{new Date(n.created*1000).toLocaleString()} · {n.delivered?'Push sent':'Saved in app'}</p>{n.error&&<small className="error">{n.error}</small>}</div><ArrowRight size={17}/></button>):<div className="empty"><Bell size={30}/><h3>Nothing to review just yet.</h3><p>Prepare a packet from your opportunity queue.</p></div>}</section><section className="panel"><h2>Take it with you.</h2><p className="muted">This dashboard adapts to your phone and iPad. Download a packet now, or configure private remote access and optional ntfy push notifications.</p><div className="caution"><span>Localhost is only reachable on this computer. Remote HTTPS access and push delivery have not been configured.</span></div><h3>Notification destination</h3><code className="url-text">{data.notification_destination||'Not configured'}</code><h3>Dashboard link</h3><code className="url-text">{data.public_app_url||'Not configured'}</code><p className="small-text">Push sends the public company/role name and a packet link to the configured service. Resume contents and answers stay in your workspace.</p><button className="secondary" disabled={!!busy} onClick={()=>run('Updating notifications',async()=>{await api('/notifications/'+(data.notifications_enabled?'disable':'enable'),data.notifications_enabled?{}:{confirmed:true});await load();})}>{data.notifications_enabled?'Disable push':'Enable push to this destination'}</button>{data.notifications_enabled&&<button className="primary" onClick={()=>run('Sending notifications',async()=>{const r=await api('/notifications/send',{});await load();setMessage(`${r.sent} notifications sent.`);})}>Send pending notifications</button>}<p className="footnote">No continuous monitoring is running by default. The optional worker polls only while you explicitly run it.</p></section></div>}
  <footer className="footer"><span><Leaf size={14}/> Built around your experience.</span><span>Originals preserved · Approvals stay yours</span></footer></main></div>;
}
